[package]
name = "physics_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
#bevy-inspector-egui = "0.37.0"
bevy = { version = "0.19", features = ["trace", "dynamic_linking"] }
bevy_diagnostic = "0.19"
bevy_egui = "0.41"
egui_plot = "0.36"
bevy_prototype_lyon = "0.17.0"
avian2d = { version = "0.7.0", features = ["debug-plugin"] }
derivative = "2.2.0"
itertools = "0.15.0"
lyon_path = "1.0.4"
num-traits = "0.2.15"
paste = "1.0.13"
ron = "0.12"
serde = { version = "1.0.171", features = ["derive"] }
strum = { version = "0.28", features = ["derive"] }
bevy_mod_debugdump = "0.16"
bevy_dylib = "0.19.0"

[features]
print-schedule = []

[package.metadata.patch.egui]
patches = [
    "egui-slider.patch"
]

[package.metadata.patch]
crates = ["egui"]

[patch.crates-io]
egui = { path = './target/patch/egui-0.35.0' }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3.17"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
tracing-wasm = "0.2"
wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 3

[[bin]]
name = "physics_rust"
path = "src/main.rs"